// Shared Components
export { AnimatedSection } from './AnimatedSection'
export type { AnimatedSectionProps } from './AnimatedSection'
export { Container } from './Container'
export type { ContainerProps } from './Container'
export { SectionHeader } from './SectionHeader'
export type { SectionHeaderProps } from './SectionHeader'
export { GlassCard } from './GlassCard'
export type { GlassCardProps } from './GlassCard'
export { BaseCard } from './BaseCard'
export type { BaseCardProps } from './BaseCard'
export { VideoContainer } from './VideoContainer'
export type { VideoContainerProps } from './VideoContainer'
export { CustomPrimaryButton } from './CustomPrimaryButton'
export type { CustomPrimaryButtonProps } from './CustomPrimaryButton'
export { FeatureList } from './FeatureList'
export type { FeatureListProps } from './FeatureList'
export { StatCard } from './StatCard'
export type { StatCardProps } from './StatCard'

export { AnimatedGrid } from './AnimatedGrid'
export type { AnimatedGridProps } from './AnimatedGrid'
export { MarqueeSection } from './MarqueeSection'
export type { MarqueeSectionProps, MarqueeItem } from './MarqueeSection'
export { Video } from './Video'
export { OptimemsLogo } from './Logo'
export { EuropeMap } from './EuropeMap'
export { Header } from './Header/Header'

// Card components
export { VideoCard as CardVideoCard } from './Card/VideoCard'
export type { VideoCardProps as CardVideoCardProps } from './Card/VideoCard'
